version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: |
          node -p process.stdout.isTTY
          echo $(tty)
    
workflows:
  version: 2
  build:
    jobs:
      - build
